# configs/bcastor_config.yaml
run_name: "dlrsm/run"
parallel: False
n_workers: 30
total_iterations: 20
initial_dataset:
  generate: true
  n_workers: 30
  n_points: 400
checkpoint: 
  name: "checkpoint"
  n_step_save: 5
resolution:
  value: 1e-6
  constant_resolution: False 
  r_decay_steps: 100
  initial: 1e-2
  final: 1e-6
batch_sampling:
  tpe_trials: 2500
  rank_samples: 30
  n_evaluation_workers: 30
  alpha: 2
eci:
  num_samples: 128