model:
  name: DLRSM
  input:
    lam1input:
      block_index: 2
      block_name: MINPAR
    lam2input:
      block_index: 3
      block_name: MINPAR
    lam3input:
      block_index: 4
      block_name: MINPAR
    lam4input:
      block_index: 5
      block_name: MINPAR
    lam5input:
      block_index: 6
      block_name: MINPAR
    lam6input:
      block_index: 7
      block_name: MINPAR
    rho1input:
      block_index: 8
      block_name: MINPAR
    rho2input:
      block_index: 9
      block_name: MINPAR
    alpha1input:
      block_index: 10
      block_name: MINPAR
    alpha2input:
      block_index: 11
      block_name: MINPAR
    alpha3input:
      block_index: 12
      block_name: MINPAR
spheno:
  model: DLRSM
  reference_slha: /home/moises/blssm-bcastor/experiments_paper/dlrsm/hepstack/SPheno-4.0.4/DLRSM/Input_Files/LesHouches.in.DLRSM_low
  directory: /home/moises/blssm-bcastor/experiments_paper/dlrsm/hepstack/SPheno-4.0.4
hep_stack:
  name: SPhenoStack
  scan_dir: /home/moises/blssm-bcastor/experiments_paper/dlrsm/datasets/scans
  final_dataset: /home/moises/blssm-bcastor/experiments_paper/dlrsm/datasets
  delete_on_exit: true
